In [133]:
#importing numpy
import numpy as np

import pandas as pd

In [134]:
read_data = pd.read_csv('Housing.csv')

In [135]:
read_data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [136]:
read_data.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [137]:
read_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [138]:
read_data.shape

(545, 13)

In [139]:

df = pd.read_csv("Housing.csv")   

# Binary Encoding
binary_cols = [
    'mainroad',
    'guestroom',
    'basement',
    'hotwaterheating',
    'airconditioning',
    'prefarea'
]

for col in binary_cols:
    read_data[col] = df[col].map({'yes': 1, 'no': 0})

# One Hot Encoding
read_data = pd.get_dummies(read_data, columns=['furnishingstatus'], drop_first=True)

print(read_data.head())
print(read_data.info())

      price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0
1  12250000  8960         4          4        4         1          0
2  12250000  9960         3          2        2         1          0
3  12215000  7500         4          2        2         1          0
4  11410000  7420         4          1        2         1          1

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1
1         0                0                1        3         0
2         1                0                0        2         1
3         1                0                1        3         1
4         1                0                1        2         0

   furnishingstatus_semi-furnished  furnishingstatus_unfurnished
0                            False                         False
1                            False                         False
2                             True                         False
3                            False                         False
4                            False                         False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            545 non-null    int64
 1   area                             545 non-null    int64
 2   bedrooms                         545 non-null    int64
 3   bathrooms                        545 non-null    int64
 4   stories                          545 non-null    int64
 5   mainroad                         545 non-null    int64
 6   guestroom                        545 non-null    int64
 7   basement                         545 non-null    int64
 8   hotwaterheating                  545 non-null    int64
 9   airconditioning                  545 non-null    int64
 10  parking                          545 non-null    int64
 11  prefarea                         545 non-null    int64
 12  furnishingstatus_semi-furnished  545 non-null    bool
 13  furnishingstatus_unfurnished     545 non-null    bool
dtypes: bool(2), int64(12)
memory usage: 52.3 KB
None

In [140]:
read_data.describe()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.858716,0.177982,0.350459,0.045872,0.315596,0.693578,0.234862
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.348635,0.382849,0.477552,0.209399,0.465180,0.861586,0.424302
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000

In [141]:
read_data.dropna(inplace=True)

In [142]:
read_data.isnull().sum()

price                              0
area                               0
bedrooms                           0
bathrooms                          0
stories                            0
mainroad                           0
guestroom                          0
basement                           0
hotwaterheating                    0
airconditioning                    0
parking                            0
prefarea                           0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [143]:
read_data.describe()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.858716,0.177982,0.350459,0.045872,0.315596,0.693578,0.234862
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.348635,0.382849,0.477552,0.209399,0.465180,0.861586,0.424302
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000

In [144]:
read_data.fillna(read_data.mean(), inplace=True)
read_data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,False,True
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,True,False
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,False,True
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,False,False
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,False,True

In [145]:
read_data.shape

(545, 14)

In [146]:
read_data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False

In [147]:
df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)

In [148]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,False,False
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,False,False
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,True,False
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,False,False
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,False,True
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,True,False
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,False,True
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,False,False
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,False,True

In [ ]:
read_data.iloc[:, 0:9].corr()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating
price,1.000000,0.535997,0.366494,0.517545,0.420712,0.296898,0.255517,0.187057,0.093073
area,0.535997,1.000000,0.151858,0.193820,0.083996,0.288874,0.140297,0.047417,-0.009229
bedrooms,0.366494,0.151858,1.000000,0.373930,0.408564,-0.012033,0.080549,0.097312,0.046049
bathrooms,0.517545,0.193820,0.373930,1.000000,0.326165,0.042398,0.126469,0.102106,0.067159
stories,0.420712,0.083996,0.408564,0.326165,1.000000,0.121706,0.043538,-0.172394,0.018847
mainroad,0.296898,0.288874,-0.012033,0.042398,0.121706,1.000000,0.092337,0.044002,-0.011781
guestroom,0.255517,0.140297,0.080549,0.126469,0.043538,0.092337,1.000000,0.372066,-0.010308
basement,0.187057,0.047417,0.097312,0.102106,-0.172394,0.044002,0.372066,1.000000,0.004385
hotwaterheating,0.093073,-0.009229,0.046049,0.067159,0.018847,-0.011781,-0.010308,0.004385,1.000000

In [7]:
import pandas as pd

data = {
    'Name': ['Ali', 'Sara', 'Omar', 'Mona', 'Youssef'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'City': ['Cairo', 'Giza', 'Cairo', 'Alex', 'Giza'],
    'Level': ['High', 'Medium', 'Low', 'Medium', 'High'],
    'Salary': [5000, 7000, 6000, 6500, 7200]
}

df = pd.DataFrame(data)

print(df)

      Name  Gender   City   Level  Salary
0      Ali    Male  Cairo    High    5000
1     Sara  Female   Giza  Medium    7000
2     Omar    Male  Cairo     Low    6000
3     Mona  Female   Alex  Medium    6500
4  Youssef    Male   Giza    High    7200

In [9]:

from sklearn.preprocessing import LabelEncoder

df_lable = df.copy()

le = LabelEncoder()

for col in ['Gender', 'City', 'Level']:
    df_lable[col] = le.fit_transform(df_lable[col])

    print(df_lable)

      Name  Gender   City   Level  Salary
0      Ali       1  Cairo    High    5000
1     Sara       0   Giza  Medium    7000
2     Omar       1  Cairo     Low    6000
3     Mona       0   Alex  Medium    6500
4  Youssef       1   Giza    High    7200
      Name  Gender  City   Level  Salary
0      Ali       1     1    High    5000
1     Sara       0     2  Medium    7000
2     Omar       1     1     Low    6000
3     Mona       0     0  Medium    6500
4  Youssef       1     2    High    7200
      Name  Gender  City  Level  Salary
0      Ali       1     1      0    5000
1     Sara       0     2      2    7000
2     Omar       1     1      1    6000
3     Mona       0     0      2    6500
4  Youssef       1     2      0    7200

In [10]:
df_one_hot = pd.get_dummies(
    df, 
    columns =['Gender', 'City', 'Level'],

    drop_first= True

)

print(df_one_hot)

      Name  Salary  Gender_Male  City_Cairo  City_Giza  Level_Low  \
0      Ali    5000         True        True      False      False
1     Sara    7000        False       False       True      False
2     Omar    6000         True        True      False       True
3     Mona    6500        False       False      False      False
4  Youssef    7200         True       False       True      False

   Level_Medium
0         False
1          True
2         False
3          True
4         False

In [11]:
df_freq = df.copy()

for col in ['Gender', 'City', 'Level']:
    freq = df_freq[col].value_counts()
    df_freq[col] = df_freq[col].map(freq)

print(df_freq)

      Name  Gender  City  Level  Salary
0      Ali       3     2      2    5000
1     Sara       2     2      2    7000
2     Omar       3     2      1    6000
3     Mona       2     1      2    6500
4  Youssef       3     2      2    7200

In [13]:
pip install category_encoders

Collecting category_encoders
  Using cached category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.3.3)
Collecting patsy>=0.5.1 (from category_encoders)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.16.3)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Using cached statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\b unit\appdata\local\programs\python\python311\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (22.0)
Using cached category_encoders-2.9.0-py3-none-any.whl (85 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 220.8 kB/s eta 0:00:42
   -- ------------------------------------- 0.5/9.6 MB 220.8 kB/s eta 0:00:42
   -- ------------------------------------- 0.5/9.6 MB 220.8 kB/s eta 0:00:42
   -- ------------------------------------- 0.5/9.6 MB 220.8 kB/s eta 0:00:42
   -- ------------------------------------- 0.5/9.6 MB 220.8 kB/s eta 0:00:42
   --- ------------------------------------ 0.8/9.6 MB 219.4 kB/s eta 0:00:41
   --- ------------------------------------ 0.8/9.6 MB 219.4 kB/s eta 0:00:41
   --- ------------------------------------ 0.8/9.6 MB 219.4 kB/s eta 0:00:41
   --- ------------------------------------ 0.8/9.6 MB 219.4 kB/s eta 0:00:41
   ---- ----------------------------------- 1.0/9.6 MB 254.2 kB/s eta 0:00:34
   ---- ----------------------------------- 1.0/9.6 MB 254.2 kB/s eta 0:00:34
   ----- ---------------------------------- 1.3/9.6 MB 297.0 kB/s eta 0:00:28
   ----- ---------------------------------- 1.3/9.6 MB 297.0 kB/s eta 0:00:28
   ----- ---------------------------------- 1.3/9.6 MB 297.0 kB/s eta 0:00:28
   ------ --------------------------------- 1.6/9.6 MB 313.0 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.6 MB 345.9 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.6 MB 345.9 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 377.7 kB/s eta 0:00:20
Resuming download statsmodels-0.14.6-cp311-cp311-win_amd64.whl (2.1 MB/9.6 MB)
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB ? eta -:--:--
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   --------- ------------------------------ 2.4/9.6 MB 53.3 kB/s eta 0:02:16
   ---------- ----------------------------- 2.6/9.6 MB 83.5 kB/s eta 0:01:24
   ---------- ----------------------------- 2.6/9.6 MB 83.5 kB/s eta 0:01:24
   ---------- ----------------------------- 2.6/9.6 MB 83.5 kB/s eta 0:01:24
   ---------- ----------------------------- 2.6/9.6 MB 83.5 kB/s eta 0:01:24
   ------------ --------------------------- 2.9/9.6 MB 108.2 kB/s eta 0:01:02
   ------------ --------------------------- 2.9/9.6 MB 108.2 kB/s eta 0:01:02
   ------------ --------------------------- 2.9/9.6 MB 108.2 kB/s eta 0:01:02
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
   ------------- -------------------------- 3.1/9.6 MB 132.6 kB/s eta 0:00:49
Resuming download statsmodels-0.14.6-cp311-cp311-win_amd64.whl (3.1 MB/9.6 MB)
   ------------- -------------------------- 3.1/9.6 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.6 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.6 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.6 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.6 MB ? eta -:--:--
   -------------- ------------------------- 3.4/9.6 MB 254.3 kB/s eta 0:00:25
   -------------- ------------------------- 3.4/9.6 MB 254.3 kB/s eta 0:00:25
   -------------- ------------------------- 3.4/9.6 MB 254.3 kB/s eta 0:00:25

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (2.1 MB/9.6 MB, attempt 1)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (3.1 MB/9.6 MB, attempt 2)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (3.4 MB/9.6 MB, attempt 3)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/bf/cc/018f14ecb58c6cb89de9d52695740b7d1f5a982aa9ea312483ea3c3d5f77/statsmodels-0.14.6-cp311-cp311-win_amd64.whl

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import category_encoders as ce

df_binary = df.copy()

encoder = ce.BinaryEncoder(cols=['Gender', 'City', 'Level'])

df_binary = encoder.fit_transform(df_binary)

print(df_binary)

      Name  Gender_0  Gender_1  City_0  City_1  Level_0  Level_1  Salary
0      Ali         0         1       0       1        0        1    5000
1     Sara         1         0       1       0        1        0    7000
2     Omar         0         1       0       1        1        1    6000
3     Mona         1         0       1       1        1        0    6500
4  Youssef         0         1       1       0        0        1    7200

In [15]:
import category_encoders as ce

df_target = df.copy()

encoder = ce.TargetEncoder(cols=['Gender', 'City', 'Level'])

df_target[['Gender', 'City', 'Level']] = encoder.fit_transform(
    df_target[['Gender', 'City', 'Level']],
    df_target['Salary']
)

print(df_target)

      Name       Gender         City        Level  Salary
0      Ali  6297.779494  6220.845105  6305.955744    5000
1     Sara  6398.158937  6447.806809  6398.158937    7000
2     Omar  6297.779494  6220.845105  6295.763119    6000
3     Mona  6398.158937  6360.817356  6398.158937    6500
4  Youssef  6297.779494  6447.806809  6305.955744    7200